'use strict';
const fs=require('node:fs');
const assert=require('node:assert/strict');
const app=fs.readFileSync('web/app.js','utf8');
const css=fs.readFileSync('web/blinq-app.css','utf8');
const ui=JSON.parse(fs.readFileSync('web/ui-config.json','utf8'));
for(const field of ['headline','text','eyebrow','headline_size','text_size','eyebrow_size','headline_color','text_color','eyebrow_color'])assert.ok(app.includes('data-simple-banner-field="'+field+'"'),field);
for(const hex of ['#000000','#303030','#555555','#808080','#b5b5b5','#e4e4e4','#ffffff'])assert.ok(app.includes(hex),hex);
for(const token of ['function syncAdminHeroPreview()','function startAdminHeroPreview()','state.adminPreviewIndex','data-admin-preview-card="desktop"','data-admin-preview-card="mobile"','data-admin-preview-pause'])assert.ok(app.includes(token),token);
for(const effect of ['fade-down','slide-up','slide-down','zoom-in','zoom-out','blur-in','diagonal-wipe','vertical-wipe','curtain-open','mosaic-grid','parallax','ken-burns','reveal-left','reveal-right','flip-in','tilt-in','focus-pulse','soft-glitch'])assert.ok(app.includes("'"+effect+"'"),effect);
for(const token of ['creative-effect-mosaic-grid','creative-effect-soft-glitch','creative-effect-vertical-wipe','creative-effect-curtain-open','creative-effect-ken-burns','creative-effect-flip-in','creative-effect-tilt-in','creative-effect-focus-pulse','creativeRevealLeft','creativeRevealRight','creativeBlurIn'])assert.ok(css.includes(token),token);
assert.ok(app.includes('bannerCreativeClasses(c)} is-active'), 'admin preview must render the selected effect');
assert.ok(app.includes('function stageAdminHeroPreviewReplay()'), 'Spustiť must replay the selected effect');
assert.ok(app.includes("const title=String(c.headline||'').trim();"));
assert.ok(!app.includes("const accent=String(c.accent_text||'').trim();"));
assert.ok(css.includes('var(--creative-headline-size,36px)'));
assert.ok(css.includes('var(--creative-headline-color,#ffffff)'));
assert.ok(app.includes('sizes([12,14,16,18,20,24,28,32,36,40,44,48,56,64,72],c.headline_size,36)'), 'heading must offer 12, 14, 16 and 18 px');
assert.ok(app.includes('n(c.headline_size,12,72,36)'), 'small headline sizes must not be clamped to 16 px');
assert.ok(app.includes('sizes([10,12,14,16,18,20,24,28],c.text_size,14)'), 'subtitle choices remain unchanged');
assert.ok(css.includes('font-size:min(var(--creative-headline-size,36px),calc(var(--creative-headline-size,36px)*.75 + 6px))!important;'), 'mobile honors small headline sizes and scales above 38 px');
assert.ok(css.includes('font-size:calc(var(--creative-headline-size,36px)*.65)!important;'), 'desktop preview scales through the full 12–72 px editor range');
assert.ok(app.includes('function adminPreviewEntry(entries=activeAdminBanners())'), 'selected unpublished banner can be previewed');
assert.ok(app.includes('state.adminPreviewPinnedId=id'), 'font edits pin the selected creative');
for(let i=1;i<=5;i++)assert.equal(ui.elements['HERO_BANNER_'+i].content.accent_text,'');
console.log('PASS: banner editor contract');
