'use strict';
const fs=require('node:fs');
const assert=require('node:assert/strict');
const app=fs.readFileSync('web/app.js','utf8');
const css=fs.readFileSync('web/blinq-app.css','utf8');
const ui=JSON.parse(fs.readFileSync('web/ui-config.json','utf8'));
for(const field of ['headline','text','eyebrow','desktop_headline_size','mobile_headline_size','desktop_text_size','mobile_text_size','desktop_eyebrow_size','mobile_eyebrow_size','headline_color','text_color','eyebrow_color','desktop_social_x','desktop_social_y','mobile_social_x','mobile_social_y','desktop_social_size','mobile_social_size'])assert.ok(app.includes('data-simple-banner-field="'+field+'"'),field);
for(const hex of ['#000000','#303030','#555555','#808080','#b5b5b5','#e4e4e4','#ffffff'])assert.ok(app.includes(hex),hex);
for(const token of ['function syncAdminHeroPreview()','function startAdminHeroPreview()','state.adminPreviewIndex','data-admin-preview-card="desktop"','data-admin-preview-card="mobile"','data-admin-preview-pause'])assert.ok(app.includes(token),token);
for(const network of ['telegram','youtube','instagram','facebook','x','tiktok'])assert.ok(app.includes("'"+network+"'"),network);
assert.ok(app.includes('data-simple-banner-field="social_${network}_text"'),'dynamic social text field binding');
assert.ok(app.includes('data-simple-banner-field="social_${network}_link"'),'dynamic social link field binding');
assert.ok(app.includes("content[`social_${network}_link`]||legacy"),'legacy social URL remains backward compatible');
for(const token of ['function bannerSocialIcon(network)','function heroSocialLinksHtml(content={},preview=false,standalone=false)','hero-slide-hitarea','hero-social-standalone'])assert.ok(app.includes(token)||css.includes(token),token);
assert.ok(css.includes('.hero-social-link{'),'social links must be styled');
assert.ok(app.includes("content[`social_${network}_text`]||networkLabel"),'social link uses editable display text');
for(const effect of ['fade-down','slide-up','slide-down','zoom-in','zoom-out','blur-in','diagonal-wipe','vertical-wipe','curtain-open','mosaic-grid','parallax','ken-burns','reveal-left','reveal-right','flip-in','tilt-in','focus-pulse','soft-glitch'])assert.ok(app.includes("'"+effect+"'"),effect);
for(const token of ['creative-effect-mosaic-grid','creative-effect-soft-glitch','creative-effect-vertical-wipe','creative-effect-curtain-open','creative-effect-ken-burns','creative-effect-flip-in','creative-effect-tilt-in','creative-effect-focus-pulse','creativeRevealLeft','creativeRevealRight','creativeBlurIn'])assert.ok(css.includes(token),token);
assert.ok(app.includes('bannerCreativeClasses(c)} is-active'), 'admin preview must render the selected effect');
assert.ok(app.includes('function stageAdminHeroPreviewReplay()'), 'Spustiť must replay the selected effect');
assert.ok(app.indexOf('admin-hero-preview-stage') < app.indexOf('admin-banner-image-editor'),'live preview must come before graphic controls');
assert.ok(app.indexOf('admin-banner-image-editor') < app.indexOf('admin-hero-selected-head'),'graphic controls must sit directly before the selected-banner editor sections');
assert.ok(app.includes("const title=String(c.headline||'').trim();"));
assert.ok(!app.includes("const accent=String(c.accent_text||'').trim();"));
assert.ok(css.includes('var(--creative-headline-size,36px)'));
assert.ok(css.includes('var(--creative-headline-color,#ffffff)'));
assert.ok(app.includes('c.desktop_headline_size??c.headline_size'),'desktop heading remains backward compatible');
assert.ok(app.includes('c.mobile_headline_size??c.desktop_headline_size??c.headline_size'),'mobile heading inherits legacy value when unset');
assert.ok(app.includes('--hero-social-x:'),'desktop social X variable exists');
assert.ok(app.includes('--hero-social-mobile-x:'),'mobile social X variable exists');
assert.ok(css.includes('var(--creative-mobile-headline-size'),'mobile headline uses its own font variable');
assert.ok(css.includes('var(--creative-mobile-text-size'),'mobile subtitle uses its own font variable');
assert.ok(css.includes('var(--hero-social-mobile-x,4%)'),'mobile social buttons have independent positioning');
assert.ok(css.includes('var(--hero-social-size,11px)'),'desktop social font size is configurable');
assert.ok(css.includes('var(--hero-social-mobile-size,10px)'),'mobile social font size is configurable');
assert.ok(app.includes('data-simple-banner-field="desktop_social_layout"'),'desktop social layout selector exists');
assert.ok(app.includes('data-simple-banner-field="mobile_social_layout"'),'mobile social layout selector exists');
assert.ok(app.includes("--hero-social-direction:"),'desktop social direction variable exists');
assert.ok(app.includes("--hero-social-mobile-direction:"),'mobile social direction variable exists');
assert.ok(css.includes('flex-direction:var(--hero-social-direction,row)'),'desktop social layout is applied');
assert.ok(css.includes('flex-direction:var(--hero-social-mobile-direction,row)'),'mobile social layout is applied');
assert.ok(app.includes('function adminPreviewEntry(entries=activeAdminBanners())'), 'selected unpublished banner can be previewed');
assert.ok(app.includes('state.adminPreviewPinnedId=id'), 'font edits pin the selected creative');
for(let i=1;i<=5;i++)assert.equal(ui.elements['HERO_BANNER_'+i].content.accent_text,'');
for(const field of ['desktop_shadow_strength','mobile_shadow_strength'])assert.ok(app.includes('data-simple-banner-field="'+field+'"'),field+' control');
for(const token of ['--hero-shadow-desktop-opacity:','--hero-shadow-mobile-opacity:','n(c.desktop_shadow_strength,0,10,10)/10','n(c.mobile_shadow_strength,0,10,10)/10'])assert.ok(app.includes(token),token);
assert.ok(css.includes('opacity:var(--hero-shadow-desktop-opacity,1)!important'),'desktop production shadow strength');
assert.ok(css.includes('opacity:var(--hero-shadow-mobile-opacity,1)!important'),'mobile production shadow strength');
assert.ok(css.includes('.lean-admin-preview.mobile::before{opacity:var(--hero-shadow-mobile-opacity,1)!important}'),'mobile preview shadow strength');
const desktopGradient="linear-gradient(90deg,rgba(2,9,12,.98) 0%,rgba(2,9,12,.94) 31%,rgba(2,9,12,.34) 43%,rgba(2,9,12,.02) 61%,rgba(2,9,12,.04) 100%)";
const mobileGradient="linear-gradient(90deg,rgba(2,15,13,.94) 0%,rgba(2,15,13,.77) 45%,rgba(2,15,13,.22) 78%,rgba(2,15,13,.35) 100%)";
assert.ok(css.includes('.lean-admin-preview.desktop::before{\\n  background:'+desktopGradient+'!important;'),'desktop preview uses public desktop gradient');
assert.ok(css.includes('.lean-admin-preview.mobile::before{\\n  background:'+mobileGradient+'!important;'),'mobile preview uses public mobile gradient');
console.log('PASS: banner editor contract');
