'use strict';
const fs=require('node:fs');
const assert=require('node:assert/strict');
const app=fs.readFileSync('web/app.js','utf8');
const css=fs.readFileSync('web/blinq-app.css','utf8');
const ui=JSON.parse(fs.readFileSync('web/ui-config.json','utf8'));
for(const field of ['headline','text','eyebrow','headline_size','text_size','eyebrow_size','headline_color','text_color','eyebrow_color'])assert.ok(app.includes('data-simple-banner-field="'+field+'"'),field);
for(const hex of ['#000000','#303030','#555555','#808080','#b5b5b5','#e4e4e4','#ffffff'])assert.ok(app.includes(hex),hex);
for(const token of ['function syncAdminHeroPreview()','function startAdminHeroPreview()','state.adminPreviewIndex','data-admin-preview-card="desktop"','data-admin-preview-card="mobile"','data-admin-preview-pause'])assert.ok(app.includes(token),token);
assert.ok(app.includes("const title=String(c.headline||'').trim();"));
assert.ok(!app.includes("const accent=String(c.accent_text||'').trim();"));
assert.ok(css.includes('var(--creative-headline-size,36px)'));
assert.ok(css.includes('var(--creative-headline-color,#ffffff)'));
assert.ok(app.includes('sizes([12,14,16,18,20,24,28,32,36,40,44,48,56,64,72],c.headline_size,36)'), 'heading must offer 12, 14, 16 and 18 px');
assert.ok(app.includes('n(c.headline_size,12,72,36)'), 'small headline sizes must not be clamped to 16 px');
assert.ok(app.includes('sizes([10,12,14,16,18,20,24,28],c.text_size,14)'), 'subtitle choices remain unchanged');
assert.ok(css.includes('font-size:min(var(--creative-headline-size,36px),clamp(18px,calc(var(--creative-headline-size,36px)*.75),38px))!important;'), 'mobile honors small headline sizes');
assert.ok(css.includes('font-size:min(var(--creative-headline-size,36px),clamp(14px,calc(var(--creative-headline-size,36px)*.65),44px))!important;'), 'desktop preview honors 12 px');
for(let i=1;i<=5;i++)assert.equal(ui.elements['HERO_BANNER_'+i].content.accent_text,'');
console.log('PASS: banner editor contract');
