-- BlinQ account/access management
-- Supabase Auth remains the source of truth for email/password/verification.
-- This migration stores product access, Telegram nick, admin role and manual payment history.

create table if not exists public.blinq_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  telegram_nick text,
  display_name text,
  role text not null default 'user' check (role in ('user','admin')),
  plan text not null default 'trial' check (plan in ('trial','pro','elite','legend','goat')),
  status text not null default 'active' check (status in ('active','locked','suspended','banned')),
  access_started_at timestamptz not null default now(),
  access_ends_at timestamptz default (now() + interval '24 hours'),
  lifetime_access boolean not null default false,
  payment_reference text,
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists blinq_profiles_email_lower_idx on public.blinq_profiles (lower(email));
create index if not exists blinq_profiles_telegram_lower_idx on public.blinq_profiles (lower(coalesce(telegram_nick,'')));
create index if not exists blinq_profiles_plan_idx on public.blinq_profiles (plan);
create index if not exists blinq_profiles_status_idx on public.blinq_profiles (status);
create index if not exists blinq_profiles_access_ends_idx on public.blinq_profiles (access_ends_at);

create table if not exists public.blinq_access_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.blinq_profiles(user_id) on delete cascade,
  changed_by uuid references auth.users(id) on delete set null,
  action text not null,
  old_plan text,
  new_plan text,
  old_status text,
  new_status text,
  old_access_ends_at timestamptz,
  new_access_ends_at timestamptz,
  payment_reference text,
  note text,
  created_at timestamptz not null default now()
);
create index if not exists blinq_access_events_user_created_idx on public.blinq_access_events (user_id, created_at desc);

create or replace function public.blinq_touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists blinq_profiles_touch_updated_at on public.blinq_profiles;
create trigger blinq_profiles_touch_updated_at
before update on public.blinq_profiles
for each row execute function public.blinq_touch_updated_at();

create or replace function public.blinq_sync_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.blinq_profiles (
    user_id, email, telegram_nick, display_name, role, plan, status,
    access_started_at, access_ends_at, lifetime_access
  ) values (
    new.id,
    coalesce(new.email,''),
    nullif(new.raw_user_meta_data->>'telegram_nick',''),
    nullif(new.raw_user_meta_data->>'display_name',''),
    'user', 'trial', 'active', now(), now() + interval '24 hours', false
  )
  on conflict (user_id) do update set
    email = excluded.email,
    telegram_nick = coalesce(excluded.telegram_nick, public.blinq_profiles.telegram_nick),
    display_name = coalesce(excluded.display_name, public.blinq_profiles.display_name),
    updated_at = now();
  return new;
end $$;

drop trigger if exists on_auth_user_blinq_profile on auth.users;
create trigger on_auth_user_blinq_profile
after insert or update of email, raw_user_meta_data on auth.users
for each row execute function public.blinq_sync_auth_user();

-- Backfill profiles for existing auth users.
insert into public.blinq_profiles (user_id,email,telegram_nick,display_name)
select id, coalesce(email,''), nullif(raw_user_meta_data->>'telegram_nick',''), nullif(raw_user_meta_data->>'display_name','')
from auth.users
on conflict (user_id) do nothing;

create or replace function public.blinq_is_admin(check_user uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1 from public.blinq_profiles p
    where p.user_id = check_user and p.role = 'admin'
  );
$$;

revoke all on function public.blinq_is_admin(uuid) from public;
grant execute on function public.blinq_is_admin(uuid) to authenticated;

alter table public.blinq_profiles enable row level security;
alter table public.blinq_access_events enable row level security;

drop policy if exists "profiles read own or admin" on public.blinq_profiles;
create policy "profiles read own or admin"
on public.blinq_profiles for select to authenticated
using (user_id = auth.uid() or public.blinq_is_admin(auth.uid()));

drop policy if exists "events admin only" on public.blinq_access_events;
create policy "events admin only"
on public.blinq_access_events for select to authenticated
using (public.blinq_is_admin(auth.uid()));

-- No direct client update/insert policies are intentionally created.
-- Access changes go only through the protected admin RPC below.

create or replace function public.blinq_admin_search_users(search_text text default '')
returns table (
  user_id uuid,
  email text,
  telegram_nick text,
  display_name text,
  role text,
  plan text,
  stored_status text,
  effective_status text,
  access_started_at timestamptz,
  access_ends_at timestamptz,
  lifetime_access boolean,
  payment_reference text,
  admin_note text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare q text := lower(trim(coalesce(search_text,'')));
begin
  if not public.blinq_is_admin(auth.uid()) then
    raise exception 'admin access required';
  end if;

  return query
  select
    p.user_id,p.email,p.telegram_nick,p.display_name,p.role,p.plan,p.status,
    case
      when p.status in ('banned','suspended','locked') then p.status
      when p.lifetime_access or p.plan='goat' then 'active'
      when p.access_ends_at is not null and p.access_ends_at > now() then 'active'
      else 'locked'
    end,
    p.access_started_at,p.access_ends_at,p.lifetime_access,
    p.payment_reference,p.admin_note,p.created_at
  from public.blinq_profiles p
  where q = ''
     or lower(p.email) like '%'||q||'%'
     or lower(coalesce(p.telegram_nick,'')) like '%'||replace(q,'@','')||'%'
     or lower(p.user_id::text) like '%'||q||'%'
  order by p.created_at desc
  limit 50;
end $$;

revoke all on function public.blinq_admin_search_users(text) from public;
grant execute on function public.blinq_admin_search_users(text) to authenticated;

create or replace function public.blinq_admin_set_access(
  target_user_id uuid,
  new_plan text,
  activation_mode text default 'reset',
  new_status text default 'active',
  new_telegram_nick text default null,
  new_payment_reference text default null,
  new_admin_note text default null
)
returns public.blinq_profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  current_row public.blinq_profiles%rowtype;
  updated_row public.blinq_profiles%rowtype;
  duration interval;
  base_time timestamptz;
  next_end timestamptz;
  next_lifetime boolean := false;
begin
  if not public.blinq_is_admin(auth.uid()) then raise exception 'admin access required'; end if;
  if new_plan not in ('trial','pro','elite','legend','goat') then raise exception 'invalid plan'; end if;
  if activation_mode not in ('reset','extend') then raise exception 'invalid activation mode'; end if;
  if new_status not in ('active','locked','suspended','banned') then raise exception 'invalid status'; end if;

  select * into current_row from public.blinq_profiles where user_id=target_user_id for update;
  if not found then raise exception 'user not found'; end if;

  if new_plan='trial' then duration := interval '24 hours';
  elsif new_plan='pro' then duration := interval '30 days';
  elsif new_plan='elite' then duration := interval '90 days';
  elsif new_plan='legend' then duration := interval '365 days';
  else duration := null; next_lifetime := true;
  end if;

  if next_lifetime then
    next_end := null;
  else
    base_time := case
      when activation_mode='extend' and current_row.access_ends_at is not null and current_row.access_ends_at > now()
        then current_row.access_ends_at
      else now()
    end;
    next_end := base_time + duration;
  end if;

  update public.blinq_profiles
  set plan=new_plan,
      status=new_status,
      access_started_at=case when activation_mode='reset' then now() else access_started_at end,
      access_ends_at=next_end,
      lifetime_access=next_lifetime,
      telegram_nick=coalesce(nullif(trim(new_telegram_nick),''),telegram_nick),
      payment_reference=nullif(trim(new_payment_reference),''),
      admin_note=new_admin_note
  where user_id=target_user_id
  returning * into updated_row;

  insert into public.blinq_access_events(
    user_id,changed_by,action,old_plan,new_plan,old_status,new_status,
    old_access_ends_at,new_access_ends_at,payment_reference,note
  ) values (
    target_user_id,auth.uid(),activation_mode,current_row.plan,updated_row.plan,current_row.status,updated_row.status,
    current_row.access_ends_at,updated_row.access_ends_at,updated_row.payment_reference,updated_row.admin_note
  );

  return updated_row;
end $$;

revoke all on function public.blinq_admin_set_access(uuid,text,text,text,text,text,text) from public;
grant execute on function public.blinq_admin_set_access(uuid,text,text,text,text,text,text) to authenticated;

create or replace function public.blinq_admin_access_history(target_user_id uuid)
returns setof public.blinq_access_events
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.blinq_is_admin(auth.uid()) then raise exception 'admin access required'; end if;
  return query select * from public.blinq_access_events where user_id=target_user_id order by created_at desc limit 100;
end $$;

revoke all on function public.blinq_admin_access_history(uuid) from public;
grant execute on function public.blinq_admin_access_history(uuid) to authenticated;

-- IMPORTANT: after creating your real admin account, promote it once in SQL Editor:
-- update public.blinq_profiles set role='admin' where email='YOUR_ADMIN_EMAIL';
-- Do not expose SUPABASE_SERVICE_ROLE_KEY in the browser.
