-- TBT model lifecycle.
--
-- Adds explicit challenger / champion / rejected states without
-- rewriting the original database migration.
--
-- The newest model that existed before this migration becomes the
-- initial champion. All older historical model versions become
-- rejected.
--
-- At most one model may be champion at any time.

alter table public.model_versions
    add column if not exists lifecycle_status text;

alter table public.model_versions
    add column if not exists promoted_at timestamptz;

alter table public.model_versions
    add column if not exists rejected_at timestamptz;

alter table public.model_versions
    add column if not exists promotion_reason text;


-- Existing rows pre-date explicit lifecycle management.
--
-- Start by marking every existing model as rejected. We then promote
-- exactly the newest historical model below.
update public.model_versions
set
    lifecycle_status = 'rejected',
    rejected_at = coalesce(rejected_at, now())
where lifecycle_status is null;


-- Preserve the currently newest model as the initial production
-- champion when no champion already exists.
with newest_model as (
    select model_version
    from public.model_versions
    order by created_at desc, model_version desc
    limit 1
)
update public.model_versions
set
    lifecycle_status = 'champion',
    promoted_at = coalesce(promoted_at, now()),
    rejected_at = null,
    promotion_reason = coalesce(
        promotion_reason,
        'Initial champion established during model lifecycle migration'
    )
where model_version = (
    select model_version
    from newest_model
)
and not exists (
    select 1
    from public.model_versions
    where lifecycle_status = 'champion'
);


-- From this point forward every newly inserted model is a challenger
-- unless promotion logic explicitly changes its status.
alter table public.model_versions
    alter column lifecycle_status
    set default 'challenger';

alter table public.model_versions
    alter column lifecycle_status
    set not null;


-- Lifecycle states are intentionally small and explicit.
do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where
            conname = 'model_versions_lifecycle_status_check'
            and conrelid = 'public.model_versions'::regclass
    ) then
        alter table public.model_versions
            add constraint model_versions_lifecycle_status_check
            check (
                lifecycle_status in (
                    'challenger',
                    'champion',
                    'rejected'
                )
            );
    end if;
end
$$;


-- PostgreSQL partial unique index guaranteeing that the database can
-- never contain two production champions simultaneously.
create unique index if not exists
    model_versions_single_champion_idx
on public.model_versions ((1))
where lifecycle_status = 'champion';


create index if not exists
    model_versions_lifecycle_created_idx
on public.model_versions (
    lifecycle_status,
    created_at desc
);


-- Explicit production model view.
create or replace view public.champion_model
with (security_invoker = true)
as
select *
from public.model_versions
where lifecycle_status = 'champion'
limit 1;


-- Public prediction view now exposes predictions generated by the
-- current champion only.
--
-- This prevents an experimental challenger from becoming visible
-- merely because its predictions were generated more recently.
create or replace view public.current_predictions
with (security_invoker = true)
as
select distinct on (p.match_id)
    p.*
from public.predictions p
join public.model_versions m
    on m.model_version = p.model_version
where m.lifecycle_status = 'champion'
order by
    p.match_id,
    p.generated_at desc;


grant select
on public.champion_model
to anon;
